<h1>Tabela de usuários</h1>

<table class="table table-striped table-hover mt-4">
    <thead class="table-dark">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Descrição</th>
        <th>Data da criação</th>
        <th>Data da modificação</th>
    </tr>
    </thead>
    <tbody>
<?php
    foreach ($block->getDados() as $item){
        echo "
            <tr>
                <td>$item[id]</td>
                <td>$item[author_name]</td>
                <td>$item[email]</td>
                <td>$item[description]</td>
                <td>$item[created_at]</td>
                <td>$item[updated_at]</td>
            </tr>
        ";
    }
    ?>
    </tbody>
</table>

